apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelab-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source: https://github.com/antheakl/kubelab-incluster
    path: apps/kubelab-app
    repoURL: 
    targetRevision: HEAD
  syncPolicy:
    automated: {}
